---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-api
  namespace: transmute-ipfs
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/enable-cors: "true"
spec:
  ports:
  - port: 5001
    name: ipfs-api-port
  - port: 8080
    name: ipfs-gateway-port
  selector:
    app: ipfs
  type: LoadBalancer