---

- name: check if nvm already installed
  stat:
    path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvm_stat

- name: create temporary directory NVM_TMP
  tempfile:
    state: directory
    suffix: NVM_TMP
  register: tmp
  when: nvm_stat.stat.isreg is not defined or not nvm_stat.stat.isreg

- name: Download nvm installer
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh
    dest: "{{ tmp.path }}/install.sh"
    mode: 0750
  when: nvm_stat.stat.isreg is not defined or not nvm_stat.stat.isreg

- name: install nvm
  shell: "{{ tmp.path }}/install.sh"
  when: nvm_stat.stat.isreg is not defined or not nvm_stat.stat.isreg

- name: Source nvm in {{ ansible_env.HOME }}/.profile
  lineinfile: dest="{{ ansible_env.HOME }}/{{ item }}" line="source ~/.nvm/nvm.sh" create=yes
  with_items: 
    - .profile
    - .bashrc

- name: Install node
  shell: 'bash -c "source {{ ansible_env.HOME }}/.profile && nvm ls-remote --lts=carbon && nvm install --lts=carbon"'
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stdout"

- name: Set default node version to carbon
  shell: 'bash -c "source {{ ansible_env.HOME }}/.profile && nvm alias default lts/carbon"'
