---
- name: register Microsoft.Network
  shell: "az provider register -n Microsoft.Network"

- name: register Microsoft.Storage
  shell: "az provider register -n Microsoft.Storage"

- name: register Microsoft.Compute
  shell: "az provider register -n Microsoft.Compute"

- name: register Microsoft.ContainerService
  shell: "az provider register -n Microsoft.ContainerService"

- name: register Microsoft.ContainerService
  shell: "az aks create {{ group_opt }} {{ nodes_opt }} {{ nodesize_opt }} {{ akscluster_opt }} {{ gensshkeys_opt }}"

- name: register Microsoft.ContainerService
  shell: "az aks get-credentials {{ akscluster_opt }} {{ group_opt }}"
  when: not dry_run