matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      language: node_js
      node_js:
        - "8.11.3"
      env:
        - TRANSMUTE_ENV='localhost'
  
cache:
  directories:
    - "node_modules"

notifications:
  slack: transmute-industries:qsGJfymYKydjgEM89Q9tPXrv

before_install:
  # Ethereum Test Dependencies
  - npm i -g ganache-cli@6.1.0 truffle@4.1.8
  - ganache-cli &>/dev/null &
  # IPFS Test Dependencies
  - wget "https://dist.ipfs.io/go-ipfs/v0.4.9/go-ipfs_v0.4.9_linux-amd64.tar.gz" -O /tmp/ipfs.tar.gz
  - pushd . && cd $HOME/bin && tar -xzvf /tmp/ipfs.tar.gz && popd
  - export PATH="$HOME/bin/go-ipfs:$PATH"
  - ipfs init
  - ipfs daemon &>/dev/null &
  - sleep 5
  - curl http://localhost:5001/api/v0/id

script:
  - npm i && lerna bootstrap

  - lerna run --scope @transmute/transmute-did coverage
  
  - lerna run --scope @transmute/transmute-adapter-memory coverage
  - lerna run --scope @transmute/transmute-adapter-orbit-db coverage
  - lerna run --scope @transmute/transmute-adapter-ipfs coverage
  - lerna run --scope @transmute/transmute-adapter-firestore coverage
  - lerna run --scope @transmute/transmute-adapter-firebase-rtdb coverage

  - lerna run --scope @transmute/transmute-framework truffle:test
  - lerna run --scope @transmute/transmute-framework truffle:migrate
  - lerna run --scope @transmute/transmute-framework coverage
  - lerna run --scope @transmute/transmute-framework test:report
