env:
  global:
    - secure: "OqvH0X/aHrfXy3OMn2Z0PrhavkhQkIYg/twdyOiO3DqvXvV+71QwL7OAXwW2GZpAdgZDPBwAxoXlo3X1aQtbsiu4zAizWCW7MRQRna9bS8T5Jv/3+D14ZW6BIxlqD4rxAvxtWnHSgNnQoF554xeCHKU3Xf/WqTXWSp9K09ai84Ye1Q+4M0Ykw2xBu8qfFICt1chXcC2A3rsSksHnAP9wgmlOvmhN2j9/U4D+qLm9xDtUoq+1dpD2hUZe636zeOIzT71N/4bRQ+oF5yTw0TevYzlTRixn5u7JVs4U1aOofYExiiJe9Nx1TlwxY5Dau5+sQZ+YjozoV85G2zoqMGYIXeSUNF2EBqBf9IZcAvlG1HIwIcC8VgPcD125f0MJGmebzEeNiM9XUykzRkwcpx2vF7WpLilT6Y0ZW8fEfhdArG9gYeSXa4ZljQ1AxlL7tgJ4NlJmR1d7N5IhJhuxi2OeEzGUb+kFIZli8w7W5gSUT9vQrY0WtC8l03Qt0DDaiC5qduI99oYzjNZ6EPgxjtuaSIRdQcFkVxb4MTUkAzwxu/A0mx+3fwQk5/VGS+YfZjZ+ILws/mZt9MCpDlGq8bO3dAUqskn6RWPU8PUpVSIFLvIp/uj2EeWBlFQDBk3dWs+4ToBhNG1gyyEeISeGgW6HgoaLOh6ABUum8J5eZgTL7eQ="

notifications:
  slack: transmute-industries:qsGJfymYKydjgEM89Q9tPXrv
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: bash
      env:
        - MINIKUBE_MEMORY=7777
        - MINIKUBE_CPU=4
        - MINIKUBE_DISK=50g
        - TRANSMUTE_RELEASE=$TRAVIS_BRANCH
        - TRANSMUTE_ENV='minikube'
        - TRANSMUTE_DO_JWT_DL=n
        - TRANSMUTE_VERBOSITY=10
        - TRANSMUTE_USE_WARN=n
        - CHANGE_MINIKUBE_NONE_USER=true
        - EDITOR=cat
before_script:
  - bash ./bootstrap
  - source ~/.bashrc
script:
  - lerna bootstrap
  - lerna run --scope transmute-adapter-firestore test
