matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: bash
      env:
        - KUBE_VERSION=v1.9.4
        - DO_JWT_DL=n
        - TRANSMUTE_VERBOSITY=10
        - CHANGE_MINIKUBE_NONE_USER=true
        - MINIKUBE_VERSION=v0.25.2
        - USE_VOX=n
        - USE_WARN=n
        - EDITOR=cat
        - MINIKUBE_MEMORY=7777
        - MINIKUBE_CPU=4
        - MINIKUBE_DISK=50g
        - MINIKUBE_DRIVER=none
        - HELM_INSTALL_DIR=$HOME/.local/bin
        - HELM_VERSION=v2.8.2
        - NVM_DIR="$HOME/.nvm"
        - HELM_SHA256=0521956fa22be33189cc825bb27b3f4178c5ce9a448368b5c81508d446472715
    # - os: linux
    #   dist: trusty
    #   sudo: required
    #   language: bash
    #   env:
    #     - KUBE_VERSION=v1.9.0
    #     - DO_JWT_DL=n
    #     - TRANSMUTE_VERBOSITY=10
    #     - CHANGE_MINIKUBE_NONE_USER=true
    #     - MINIKUBE_VERSION=v0.25.2
    #     - USE_VOX=n
    #     - USE_WARN=n
    #     - EDITOR=cat
    #     - MINIKUBE_MEMORY=7777
    #     - MINIKUBE_CPU=4
    #     - MINIKUBE_DISK=50g
    #     - MINIKUBE_DRIVER=none
    #     - HELM_INSTALL_DIR=$HOME/.local/bin
    #     - HELM_VERSION=v2.8.2
    #     - NVM_DIR="$HOME/.nvm"
    #     - HELM_SHA256=0521956fa22be33189cc825bb27b3f4178c5ce9a448368b5c81508d446472715
    #   cache:
    #     directories:
    #       - /home/travis/.minikube
    #       - /home/travis/.local
    #       - /home/travis/.nvm
    # - os: linux
    #   dist: trusty
    #   sudo: required
    #   language: bash
    #   env:
    #     - KUBE_VERSION=v1.8.0
    #     - DO_JWT_DL=n
    #     - TRANSMUTE_VERBOSITY=10
    #     - CHANGE_MINIKUBE_NONE_USER=true
    #     - MINIKUBE_VERSION=v0.25.2
    #     - USE_VOX=n
    #     - USE_WARN=n
    #     - EDITOR=cat
    #     - MINIKUBE_MEMORY=7777
    #     - MINIKUBE_CPU=4
    #     - MINIKUBE_DISK=50g
    #     - MINIKUBE_DRIVER=none
    #     - HELM_INSTALL_DIR=$HOME/.local/bin
    #     - HELM_VERSION=v2.8.2
    #     - NVM_DIR="$HOME/.nvm"
    #     - HELM_SHA256=0521956fa22be33189cc825bb27b3f4178c5ce9a448368b5c81508d446472715
      # cache:
      #   directories:
      #     - /home/travis/.minikube
      #     - /home/travis/.local
      #     - /home/travis/.nvm
      #     - /home/travis/.transmute


before_script:
  # boostrap installs global dev dependencies, including the transmute-cli
  - TRANSMUTE_RELEASE=$TRAVIS_BRANCH ./bootstrap
  # This next line should be moved into boostrap...
  - . $HOME/.nvm/nvm.sh
  # This setup overwrites the transmute-cli with a build from the current branch (so the cli is tested)
  - cd $TRAVIS_BUILD_DIR/packages/transmute-cli
  - npm i -g
  - cd $TRAVIS_BUILD_DIR
  - transmute k8s provision-minikube travis_test_cluster --vmdriver none
  - transmute k8s init travis_test_cluster
  # potentially un needed, should be moved into cli
  # - minikube update-context
  - sleep 8
  - kubectl get pods --all-namespaces
  - kubectl get svc --all-namespaces
  - kubectl describe pod $(kubectl get pod --all-namespaces|grep gateway-kong-migrations|awk '{print $2}')
  - kubectl describe pod $(kubectl get pod --all-namespaces|grep -v gateway-kong-migrations|grep gateway-kong|awk '{print $2}')

script:
  - lerna bootstrap
  - TRANSMUTE_ENV='minikube' lerna run --scope transmute-framework truffle:test
  - TRANSMUTE_ENV='minikube' lerna run --scope transmute-framework truffle:migrate
  - TRANSMUTE_ENV='minikube' lerna run --scope transmute-framework test
  - TRANSMUTE_ENV='minikube' lerna run --scope transmute-framework test:report



