
notifications:
  slack: transmute-industries:qsGJfymYKydjgEM89Q9tPXrv
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: bash
      env:
        - MINIKUBE_MEMORY=7777
        - MINIKUBE_CPU=4
        - MINIKUBE_DISK=50g
        - TRANSMUTE_RELEASE=$TRAVIS_BRANCH
        - TRANSMUTE_ENV='minikube'
        - TRANSMUTE_DO_JWT_DL=n
        - TRANSMUTE_VERBOSITY=10
        - TRANSMUTE_USE_WARN=n
        - CHANGE_MINIKUBE_NONE_USER=true
        - EDITOR=cat
before_script:
  - bash ./bootstrap
  - source ~/.bashrc
script:
  - lerna bootstrap
  - lerna run --scope transmute-adapter-firestore test
