version: '2'
services:

  testrpc:
    environment:
      - RPC_HOST=testrpc
    build: ./packages/transmute-cli/components/ganache/docker/ganache-cli
    ports:
      - "8545:8545"

  ipfs:
    build: ./packages/transmute-cli/components/ipfs/docker/ipfs
    ports:
     - "8080:8080"
     - "5001:5001"
     - "4001:4001"
    #  Uncomment this if you want to persist your IPFS data locally
    #  Otherwise it will always be a new instance (no persistence)
    # volumes:
    #   - ~/.ipfs/:/data/ipfs/
    
