---
- name: k8s-install-kong
  hosts: localhost
  connection: local
  vars:
    ipfs_started: no
    ganache_started: no
    kong_proxy_port: 32443
  gather_facts: yes
  roles:
    - role: kong
    - role: ganache-kong-ipfs
      when: ganache_started and ipfs_started
