---
- name: k8s-install-istio
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    microservice:
      name: istio
      namespace: istio-system
      helm:
        dest: "{{ ansible_env.HOME }}/.transmute/git/istio"
        repo: "https://github.com/istio/istio.git"
        version: "{{ tranmsute_istio_version }}"
        chart:
          path: "install/kubernetes/helm/istio"
        flags: >-
          --set "gateways.istio-ingressgateway.type=NodePort"
          --set "gateways.istio-egressgateway.type=NodePort"
  roles:
    - role: k8s-install-microservice-with-local-helm-chart
