---
- name: generate {{ ansible_env.HOME }}/.transmute/.env
  template:
    src: ".env.j2"
    dest: "{{ ansible_env.HOME }}/.transmute/.env"

- name: Install npm packages globally
  shell: 'bash -c "source {{ ansible_env.HOME }}/.nvm/nvm.sh  && npm i -g transmute-cli"'
  become: no
