apiVersion: v1
appVersion: v0.1.0
description: A Helm chart for the Interplanetary File System
home: https://ipfs.io/
icon: https://raw.githubusercontent.com/ipfs/logo/master/raster-generated/ipfs-logo-128-ice-text.png
keywords:
- ipfs
- distributed-web
maintainers:
- email: orie@transmute.industries
  name: OR13
name: ipfs
sources:
- https://github.com/ipfs/go-ipfs
version: 0.2.0
