---

- name: touch {{ ansible_env.HOME }}/.zshrc
  file:
    path: "{{ ansible_env.HOME }}/.zshrc"
    state: touch

- name: touch {{ ansible_env.HOME }}/.bashrc
  file:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: touch

- name: set TRANSMUTE_BIN variable
  set_fact: transmute_bin="{{ ansible_env.HOME }}/.transmute/bin"

- name: Create dir {{ transmute_bin }}
  file:
    path: "{{ transmute_bin }}"
    state: directory

- name: add PATH to {{ ansible_env.HOME }}/.zshrc and {{ ansible_env.HOME }}/.bashrc
  lineinfile:
    path: "{{ item }}"
    line: 'export PATH={{ transmute_bin }}:$PATH'
  with_items:
    - "{{ ansible_env.HOME }}/.zshrc"
    - "{{ ansible_env.HOME }}/.bashrc"
