apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ipfs-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "ipfs.servicename" . }}
          servicePort: 5001