apiVersion: v1
kind: Service
metadata:
  name: ganache-lb
spec:
  ports:
    - port: 9967
      name: http
      targetPort: 8545
  selector:
    name: ganache
  sessionAffinity: None
  type: LoadBalancer