---
- name: Cloning {{ microservice.name | capitalize }} ({{ microservice.helm.repo }}, {{ microservice.helm.version }}) into {{ microservice.helm.dest }}
  git:
    repo: "{{ microservice.helm.repo }}"
    dest: "{{ microservice.helm.dest }}"
    version: "{{ microservice.helm.version }}"
    accept_hostkey: yes
    depth: 1

- name: Checking Helm release status of {{ microservice.name }}
  shell: helm list --deployed "^{{ microservice.name }}$"
  register: helm_release_status_check
  changed_when: no
  check_mode: no

- block:
    - name: Installing {{ microservice.name | capitalize }} with local Helm chart
      shell: >
        helm install "{{ microservice.helm.dest + '/' + microservice.helm.chart.path }}"
        --name "{{ microservice.name }}"
        --namespace "{{ microservice.namespace }}"
        {{ microservice.helm.flags }}
    - name: Wait for {{ microservice.name | capitalize }} to be ready
      shell: "$(npm root -g)/transmute-cli/scripts/w8s/ready.w8 istio istio-system"
      changed_when: no
  when: helm_release_status_check.stdout == ""
